### ISSUE TITLE
Cannot mount more than RPC_Max_Connections value over time

### ISSUE THREAD

**Issue by CyrilPeponnet** [nfs-ganesha/nfs-ganesha#270]
**Environment**

Centos 7.4, nfs-ganesha 2.5.2 and 2.5.5

**Configuration**

```
EXPORT{
    Export_Id = 2 ;
    Path = "/export/raid/bricks/hdd/homedirs";

    FSAL {
        name = VFS;
    }

    Access_type = RW;
    Squash = no_root_squash;
    Disable_ACL = TRUE;
    Pseudo = "/homedirs";
    Tag = "homedirs";
    Protocols = "3","4" ;
    Transports = "UDP","TCP" ;
    SecType = "sys";
}
```

**Issue**

This setup have ~255 clients that regularly reboots (virtual machines for QA tests). After few days the rebooted machine can no longer mount, and the message

```
ganesha.nfsd[31891]: [work-239] nfs_rpc_create_chan_v41 :NFS CB :WARN :can not create back channel, code 22
```
is logged on the nfs-ganesha server

**reduction**

On another server with the same configuration, if I issue

```
a=0; while true; do mount -t nfs localhost:/homedirs /media && umount /media && let a++&& echo $a; done
```

on a fresh started server, it stoped to work (mount is hanging) around the 1024 time.

**debug logs**

Ran with `ganesha.nfsd -N DEBUG -F`

```
Feb 28 15:08:03 zboub ganesha.nfsd[31891]: [work-30] nfs4_op_lookup :EXPORT :DEBUG :PSEUDO FS JUNCTION TRAVERSAL: Crossed to /homedirs, id=2 for name=homedirs
Feb 28 15:08:03 zboub ganesha.nfsd[31891]: [work-30] nfs4_Compound :NFS4 :DEBUG :Request 3: opcode 10 is OP_GETFH
Feb 28 15:08:03 zboub ganesha.nfsd[31891]: [work-30] nfs4_Compound :NFS4 :DEBUG :Request 4: opcode 9 is OP_GETATTR
Feb 28 15:08:03 zboub ganesha.nfsd[31891]: [work-30] file_To_Fattr :NFS4 ACL :DEBUG :No permission check for ACL for obj 0x55a3071fbe18
Feb 28 15:08:03 zboub ganesha.nfsd[31891]: [work-30] encode_fsid :NFS4 :DEBUG :fsid.major = 13424068183129380207, fsid.minor = 1271801303055537546
Feb 28 15:08:03 zboub ganesha.nfsd[31891]: [disp] nfs_rpc_cond_stall_xprt :DISP :DEBUG :xprt 0x7f2684001170 xp_refs 3 has 0 reqs active (max 512)
Feb 28 15:08:03 zboub ganesha.nfsd[31891]: [decoder] thr_decode_rpc_request :DISP :DEBUG :0x7f2684001170 context (nil)
Feb 28 15:08:03 zboub ganesha.nfsd[31891]: [decoder] nfs_rpc_enqueue_req :DISP :DEBUG :enqueued req, q 0x55a305f39960 (REQ_Q_LOW_LATENCY 0x55a305f39960:0x55a305f399c8) size is 1 (enq 22560 deq 22559)
Feb 28 15:08:03 zboub ganesha.nfsd[31891]: [decoder] thr_decode_rpc_requests :DISP :DEBUG :exiting, stat=XPRT_IDLE
Feb 28 15:08:03 zboub ganesha.nfsd[31891]: [work-32] worker_run :DISP :DEBUG :NFS protocol request, reqdata=0x7f26840008c0 xprt=0x7f2684001170 requests=1
Feb 28 15:08:03 zboub ganesha.nfsd[31891]: [work-32] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 0
Feb 28 15:08:07 zboub kernel: NFS: state manager: bind conn to session failed on NFSv4 server localhost with error 121
Feb 28 15:08:07 zboub ganesha.nfsd[31891]: [work-239] nfs_rpc_create_chan_v41 :NFS CB :WARN :can not create back channel, code 22
Feb 28 15:08:08 zboub kernel: NFS: state manager: bind conn to session failed on NFSv4 server localhost with error 121
Feb 28 15:08:09 zboub kernel: NFS: state manager: bind conn to session failed on NFSv4 server localhost with error 121
Feb 28 15:08:10 zboub kernel: NFS: state manager: bind conn to session failed on NFSv4 server localhost with error 121
```

Full log (360k lines) can be found here: https://www.dropbox.com/s/k7h2wvya1jsjwan/full_log?dl=0

**Comment by CyrilPeponnet** [comment]
Looks like directly related to:

```
        RPC_Max_Connections = X;
```

Settings that has 1024 as default value and 10000 has a maximum.

Looks like connection are not recycled somehow and even with 10k as a maxium I cannot hold the week without a lock.

**Comment by CyrilPeponnet** [comment]
Tried with 2.6 leads to core dump (rpc.max_connections set to 100)

```
28/02/2018 16:06:10 : epoch 5a9743db : Zboub_server : nfs-ganesha-10792[svc_5] rpc :TIRPC :DEBUG :makefd_xprt: fd 44 max_connections exceeded

28/02/2018 16:06:10 : epoch 5a9743db : Zboub-server : nfs-ganesha-10792[svc_5] rpc :TIRPC :DEBUG :clnt_vc_ncreatef: fd 44 svc_fd_ncreatef failed
Segmentation fault (core dumped)
```

**Comment by CyrilPeponnet** [comment]
Looking at the code looks like svc_vc_destroy from libntirpc is never called so 

```
	/* connection tracking--decrement now, he's dead jim */
	svc_vc_dec_nconns();
```

Never run and 

```
svc_vc_new_conn_ok(void)
{
	bool ok = false;
	svc_cond_init();
	mutex_lock((&__svc_params->xprt_u.vc.mtx));
	if (__svc_params->xprt_u.vc.nconns < __svc_params->max_connections) {
		++(__svc_params->xprt_u.vc.nconns);
		ok = true;
	}
	mutex_unlock(&(__svc_params->xprt_u.vc.mtx));
	return (ok);
}

#define svc_vc_dec_nconns() \
	do { \
		mutex_lock((&__svc_params->xprt_u.vc.mtx)); \
		--(__svc_params->xprt_u.vc.nconns); \
		mutex_unlock(&(__svc_params->xprt_u.vc.mtx)); \
	} while (0)

```

The `vc.nconns1st will grow each time there is a new mount until it reached the hard limit.

**Comment by dang** [comment]
This must mean there's a session refcount leak somewhere, as the connection is destroyed in:
dec_session_ref() ->
nfs_rpc_destroy_chan() ->
_nfs_rpc_destroy_chan()

I'll see if I can figure this out.

**Comment by dang** [comment]
Okay, the crash on 2.6 (or more properly ntirpc-1.6) is fixed by https://github.com/nfs-ganesha/ntirpc/pull/107

That leaves 2.6 behaving like 2.5, so I'll work on that problem next.

**Comment by dang** [comment]
https://github.com/nfs-ganesha/ntirpc/pull/108

This fixes the problem on 1.6.  I'll look into backporting to 1.5, at least, as soon as it's merged.

**Comment by dang** [comment]
(sorry, 1.7; it will be backported to 1.6 also)

**Comment by CyrilPeponnet** [comment]
Ok, let me know when it will be backported. As 2.6 still didn't hit the release repo for Centos7 I guess that it will take time before I can use this patches release. (even if I think this issue is still pretty serious for a production use case). Thanks :)

**Comment by M-Carter** [comment]
We still have a similar issue.  Is this related or should I open a separate report?

VERSIONS:
nfs-ganesha: 2.7.6-2
os: Oracle Linux Server 7.7
kernel: 4.19.59-1.19.59
ZFS: 0.8.2
FSAL: VFS
All ganesha settings are defaults.

VMWare mounts the ganesha share, version 3.  Underlying filesystem is on ZFS.  Some of our NFS servers are nvme, the others are on rotational disks.  The ones where we are specifically reproducing this issue are all on nvme.

VMs are running a Citrix VDI environment.  Spinning up specific VMs immediately saturates max connections.  These errors will flood into the ganesha.log and stalls the connection for all ESXi machines in that vcenter.  Errors return if the ganesha service is restarted, and errors do not stop until those machines are shut down.

We attempted to increase RPC_Max_Connections to the maximum, 10000. This just took a few moments longer to reach the same issue.

Error state is consistently reproducible by booting these specific VMs.  We tried moving the VM storage to 3 different nvme servers in our environment. it happens on each one of them.

This issue has happened sporadically throughout our ganesha shares, but this is the first time we’ve been able to reliably reproduce the problem.

We switched the NFS mounts from ganesha to kernel NFS and these VMs booted without issue.  For some reason it works with kernel NFS, but breaks with ganesha.

```
30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_35] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10126 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10125 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :clnt_vc_ncreatef: fd 10125 svc_fd_ncreatef failed
30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10126 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_7] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10127 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :clnt_vc_ncreatef: fd 10126 svc_fd_ncreatef failed
30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_65] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10127 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_27] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10127 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_28] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10127 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10126 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :clnt_vc_ncreatef: fd 10126 svc_fd_ncreatef failed
30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10127 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_66] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10129 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :clnt_vc_ncreatef: fd 10127 svc_fd_ncreatef failed
30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_29] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10128 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_48] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10128 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_49] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10128 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10127 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :clnt_vc_ncreatef: fd 10127 svc_fd_ncreatef failed
30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10128 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :clnt_vc_ncreatef: fd 10128 svc_fd_ncreatef failed
30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_37] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10129 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_25] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10128 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_36] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10128 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10130 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :clnt_vc_ncreatef: fd 10130 svc_fd_ncreatef failed
30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_20] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10129 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10128 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :clnt_vc_ncreatef: fd 10128 svc_fd_ncreatef failed
30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_12] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10129 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_44] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10129 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_10] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10129 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10128 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :clnt_vc_ncreatef: fd 10128 svc_fd_ncreatef failed
30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_52] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10131 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10129 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :clnt_vc_ncreatef: fd 10129 svc_fd_ncreatef failed
30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_45] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10131 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_18] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10131 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[svc_42] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10131 max_connections 10000 exceeded

30/03/2020 13:30:30 : epoch 5e822c2a : <hostname redacted> : ganesha.nfsd-5509[Admin] rpc :TIRPC :EVENT :svc_xprt_lookup: fd 10129 max_connections 10000 exceeded
```

**Comment by dang** [comment]
Definitely not the same issue, since that one was fixed before 2.7 was released.

**Comment by M-Carter** [comment]
Thank you, I'll open a new report.

**Comment by ffilz** [comment]
Closing as resolved.
