### ISSUE TITLE
when trying to add share using dbus-send ganesha crashes

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#548]
When trying to add share using dbus-send:
dbus-send --print-reply --system --dest=org.ganesha.nfsd
/org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport
string:/dir string:"EXPORT(Path=/dir)"

ganesha fails with message in log:
05/02/2018 11:07:24 : epoch 5a783806 : ocata-ceph-node1 : ganesha.nfsd-31119[dbus_heartbeat] unregister_fsal :FSAL :CRIT :Unregister FSAL VFS with non-zero refcount=2

With version 3.2 the problem is still present:
02/03/2020 10:29:11 : epoch 5e5cd1e2 : nfsrefer-02 : ganesha.nfsd-62438[dbus_heartbeat] unregister_fsal :FSAL :CRIT :Unregister FSAL VFS with non-zero refcount=1

The corresponding Debian bug is: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=889654

**Comment by dang** [comment]
What FSAL are you using?  Can you post any related messages in the log?

**Comment by christmart** [comment]
We are using FSAL_VFS.
And even if I put all logging to DEBUG I get only this one line of error after issuing the dbus-send command.

**Comment by dang** [comment]
Try FULL_DEBUG

**Comment by malahal** [comment]
The parser is crashing while parsing the file given if the file is actually a directory. I imagine your /dir is a directory but what you need to give is a config file there. We should fix the config parser. The following should work provided you have your /dir export defined in that file /etc/ganesha/ganesha.conf. How about using ganesha_mgr command to add exports?

dbus-send --print-reply --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/ganesha.conf string:"EXPORT(Path=/dir)"

**Comment by ffilz** [comment]
Looks like a legitimate bug we should address.

**Comment by ffilz** [comment]
Ok, I added a check of the file before calling the parser. We verify we can stat the file and that it is a regular file. Inability of Ganesha to actually read from the file or EIO errors will still crash Ganesha, but this is a simple fix without trying to understand how to dig into the Flex parser...

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/498974

**Comment by ffilz** [comment]
Closing as resolved.
